POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWNrZXJAZXhhbXBsZS5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2ODMyMDY2NSwiZXhwIjoxNzY4MzI0MjY1fQ.me5IwtqQ7rREgRzzd4hLRPGDZO4zXh1tl7uJHGoK0Es

{
    "name": "iPhone 6s",
    "description": "Latest Apple flagship phone in UK",
    "price": 400.00
}


