version: '3.9'
services:
  mysql:
    image:  mysql:latest
    container_name: inventory_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventorydb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql


